### ISSUE TITLE
Weekly Scrum - 04/04/21

### ISSUE THREAD

**Issue by simonkrol** [simonkrol/YouWantToPlayFrontendBackend#38]

**Comment by simonkrol** [comment]
### What have I done this week?
- Started on shop search functionality #34 
### What will I work on next week?
- Continue on Shop Search #34 
### Any Blockers?
- Nope

**Comment by seangordean** [comment]
### What have I done this week?
- Started work on shopping cart #35

### What will I do next week?
- Finish shopping cart #35 
### Am I blocked?
- Nope

**Comment by BoyanSiromahov** [comment]
### What have I done this week?
- Looked into methods to add images for products #33
### What will I work on next week?
- Implement images for products #33
### Any Blockers?
- None

**Comment by GordonMacDonald16** [comment]
### What have I done this week?
- Deployed application to gcp
### What will I work on?
- Configuring Grafana and Prometheus
### Any Blockers?
- No

**Comment by L-Murphy** [comment]
### What have I done this week?
- Started on shopping cart #35  
### What will I work on next week?
- Continue on shopping cart #35 
### Any Blockers?
- Nope
